Select Count(1) From  SAS_PULSE_STG.CONS_REGIONAL_CHANNELS_OLD;---19
Select Count(1) From  SAS_PULSE_STG.CONS_REGIONAL_CHANNELS; --139

Delete SAS_PULSE_STG.CONS_REGIONAL_CHANNELS_OLD;
Insert Into SAS_PULSE_STG.CONS_REGIONAL_CHANNELS_OLD
Select * From SAS_PULSE_STG.CONS_REGIONAL_CHANNELS;
	
	
delete from SAS_PULSE_STG.CONS_REGIONAL_CHANNELS;

INSERT INTO SAS_PULSE_STG.CONS_REGIONAL_CHANNELS (BUSINESS_UNIT_ID, LOCAL_CHANNEL, COUNTRY_NAME,
	GLOBAL_REGION, CONSUMER_REGION, WEIGHTING_GROUP, INSERT_DTTM, INSERT_ID)
SELECT ch.BU_ID AS BUSINESS_UNIT_ID, TRIM(ch.LCL_CHNL_CODE) AS LOCAL_CHANNEL, TRIM(pgh.ctry_desc) 
	AS COUNTRY_NAME, TRIM(pgh.RGN_DESC) AS GLOBAL_REGION, TRIM(crc.CONSUMER_REGION)AS CONSUMER_REGION, TRIM(crc.WEIGHTING_GROUP)AS WEIGHTING_GROUP, 
	CAST(CAST(CURRENT_DATE AS CHAR(10)) || CAST(CURRENT_TIME AS CHAR(8)) AS DECIMAL(18)), 'Rodney Gross' AS INSERT_ID
FROM corp_drm_pkg.chnl_hier ch
	INNER JOIN corp_drm_pkg.PHYS_GEO_HIER pgh
	ON ch.bu_id = pgh.bu_id
	INNER JOIN SAS_PULSE_STG.CONS_REGIONAL_CHANNELS_OLD crc
	ON pgh.bu_id = crc.business_unit_id
WHERE (pgh.ISO_CTRY_CODE_2 IN('US','CA','BR','MX','GB',
	'FR','DE','JP','CN','IN','AU') AND
	ch.CUST_TYPE_CODE = 'CBOCH' AND ch.SEG_ABBR IN ('CONSOC','CSEPPC','COSLHC','COSLAC','COSLOC')) OR 
	(ch.BU_ID = 3232 AND ch.LCL_CHNL_CODE = 'OH') OR (ch.BU_ID = 1717 AND ch.LCL_CHNL_CODE = '21862')
GROUP BY 1,2,3,4,5,6,7,8;



COLLECT STATISTICS ON SAS_PULSE_STG.CONS_REGIONAL_CHANNELS COLUMN(BUSINESS_UNIT_ID, LOCAL_CHANNEL);


Select Count(1) From SAS_PULSE_STG.CONS_REGIONAL_CHANNELS_OLD; --139
Select Count(1) From SAS_PULSE_STG.CONS_REGIONAL_CHANNELS; ----137
